name: Build and Deploy native-image to Cloud Run

on:
  push:
    branches:
    - main
    
env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: europe-west6
  SERVICE_NAME: talkapi-native
    
jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}
        
    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
         java-version: 11
         
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
         path: ~/.m2
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-m2     
       
    - name: Build with Maven (with GraalVM)
      run: mvn -B clean spring-boot:build-image --file talkapi-native/pom.xml
       
    - name: Push docker image native
      run: |-
        docker push "gcr.io/$PROJECT_ID/$SERVICE_NAME:latest"
       
    # Deploy image to Cloud Run
    - name: Deploy native-image
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:latest" \
          --platform "managed" \
          --allow-unauthenticated
